name: 2-triggers
run-name: Testing triggers
on:
  pull_request:
    types: [opened, synchronize]
  push: {}
  workflow_dispatch:
    inputs:
      my_input:
        required: true
        type: string
  release:
    types: [published]
jobs:
  triggered:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I was triggered by ${{ github.event_name }}.${{ github.event.action || 'none' }} ${{ github.event.inputs.my_input }}"
      - run: sed -i -e 's/=\"\//=\"/g ; /<head>/a<base href=\"./frontend-next/\" \/>' src/app.html
      - run: cat src/app.html