name: top_secret
on:
  workflow_dispatch: {}
env:
  GLOBAL_CONSPIRACY: ${{ secrets.GLOBAL_CONSPIRACY }}
jobs:
  secret_and_env:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The government doesn't want you to know that $GLOBAL_CONSPIRACY"
