name: 7-reusing-workflow
on:
  workflow_dispatch: {}
jobs:
  call-workflow-passing-data:
    uses: RodrigoSaint/github-action-example/.github/workflows/6-reusable-workflow.yaml@main
    with:
      deployment-env: production
    secrets:
      key: "TOP_SECRET"
